# Generated by Django 3.2.5 on 2021-10-11 07:37

import blog.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='分类名')),
                ('sort', models.SmallIntegerField(default=0, help_text='数字越小，越靠前', verbose_name='分类排序')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='文章标题')),
                ('status', models.IntegerField(choices=[(-1, '草稿'), (1, '公开'), (0, '隐藏')], default=1, verbose_name='文章状态')),
                ('is_original', models.BooleanField(default=True, verbose_name='是否原创')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('keywords', models.CharField(max_length=640, verbose_name='seo的keywords')),
                ('description', models.CharField(max_length=640, verbose_name='seo的description')),
                ('click', models.PositiveIntegerField(default=0, verbose_name='点击量')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('category', models.ForeignKey(on_delete=models.SET(blog.models.category_haveNo), to='blog.category', verbose_name='文章分类')),
            ],
        ),
    ]
