# Generated by Django 3.2.5 on 2021-10-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort'], 'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, max_length=640, null=True, verbose_name='seo的description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.CharField(blank=True, max_length=640, null=True, verbose_name='seo的keywords'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(1, '公开'), (0, '隐藏')], default=1, verbose_name='文章状态'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort',
            field=models.SmallIntegerField(default=0, help_text='数字越小，排名越靠前', verbose_name='分类排序'),
        ),
    ]
