# Generated by Django 3.2.5 on 2021-10-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211011_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='status',
        ),
        migrations.AddField(
            model_name='article',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='是否公开'),
        ),
    ]
