# Generated by Django 3.2.5 on 2021-10-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211011_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='content_html',
            field=models.TextField(blank=True, help_text='返回给客户端', null=True, verbose_name='文章内容html'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_markdown',
            field=models.TextField(blank=True, help_text='提交的元数据', null=True, verbose_name='文章内容markdown'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_original',
            field=models.BooleanField(default=True, help_text='文章是否原创，不勾选就是转载', verbose_name='是否原创'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_public',
            field=models.BooleanField(default=True, help_text='文章是否公开展示，不勾选就对外隐藏', verbose_name='是否公开'),
        ),
    ]
