# Generated by Django 3.2.5 on 2021-10-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211011_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_html',
            field=models.TextField(blank=True, help_text='返回给客户端(根据markdown自动生成的，不要手动修改)', null=True, verbose_name='文章内容html'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_markdown',
            field=models.TextField(blank=True, null=True, verbose_name='文章内容markdown'),
        ),
    ]
