# Generated by Django 3.2.5 on 2021-10-15 07:18

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211011_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-sort', '-created'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-sort'], 'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AddField(
            model_name='article',
            name='sort',
            field=models.SmallIntegerField(default=0, help_text='数字越大，排名越靠前；首先根据该值排序，若文章的该值一样，那最新的文章排前面', verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=blog.models.category_haveNo, on_delete=django.db.models.deletion.SET_DEFAULT, to='blog.category', verbose_name='文章分类'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort',
            field=models.SmallIntegerField(default=0, help_text='数字越大，排名越靠前', verbose_name='分类排序'),
        ),
    ]
