# Generated by Django 3.2.5 on 2021-10-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211015_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sort',
            field=models.SmallIntegerField(default=0, help_text='数字越大，排名越靠前；首先根据该值排序，若文章的该值一样，那最新的文章排前面', verbose_name='权重'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort',
            field=models.SmallIntegerField(default=0, help_text='数字越大，排名越靠前', verbose_name='权重'),
        ),
    ]
